### ISSUE TITLE
ImportError: cannot import name 'Parser' from 'pyflp'

### ISSUE THREAD

**Issue by hoffr** [demberto/FLPInspect#3]
complete python noob. the docs for this and flpinspect are really not good enough for someone like me, i have no idea what i'm doing. i just wanna replace paths of project .wavs with .flacs so i can save disk space, lol. i don't even know if this can do that

after installing requirements.txt and flpinspect (globally, no venv because it confuses me), i have no idea how to run it. i try __main__ and i get errors, so i take it up online and someone tells me to use python -m, but i get an error basically telling me i need pyflp. isn't that what requirements was supposed to install? there weren't any errors when i did it, but i didn't specifically check to see what was installed, but there were definitely some things installed

well i went and installed pyflp anyway via the method described on its github readme, and this time it actually installed. so i run flpinspect, but now i get this:

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Hoffry\AppData\Roaming\Python\Python310\site-packages\flpinspect\__main__.py", line 4, in <module>
    from .inspector import FLPInspector
  File "C:\Users\Hoffry\AppData\Roaming\Python\Python310\site-packages\flpinspect\inspector.py", line 8, in <module>
    from pyflp import Parser
ImportError: cannot import name 'Parser' from 'pyflp' (C:\Users\Hoffry\AppData\Roaming\Python\Python310\site-packages\pyflp\__init__.py)
```

**Comment by demberto** [comment]
Ahh well, I can't go too deep into the basics. A decent knowledge of Python is required to use PyFLP. However I will help you with what you want to achieve.

> i just wanna replace paths of project .wavs with .flacs so i can save disk space, lol. i don't even know if this can do that

Its very well possible. Almost everything you see in the Sampler can be modified by PyFLP.

Also, can you please open a discussion at https://github.com/demberto/PyFLP/discussions to continue this discussion there?

**Btw, currently FLPInspect is unusable and very broken, so sorry about that. I should make it clear in the README**.

*I never really thought it would be any use to people*. I am however working on a rewrite but its not going to happen soon enough.
